version: '3'

services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    networks:
      - frontend
      - backend
    depends_on:
      - redis
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - backend
    depends_on:
      - db
    restart: always

  worker:
    build: ./worker
    networks:
      - backend
    depends_on:
      - redis
      - db
    restart: always

  redis:
    image: redis:alpine
    networks:
      - backend
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:

volumes:
  db-data: