version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo